[package]
name = "fhia"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0.100"
chumsky = {version = "0.12.0", features = ["nightly", "lexical-numbers", "debug"]}
clap = {version = "4.5.31", features = ["derive"]}
logos = "0.16.1"
